const f = ()=> {
try {
    let a  = 0;
    console.log("Program run successfully");
    // console.log(Sabita)
    return;
} catch (error) {
    console.log("This is an error");
    console.log(Babita)
}
finally{
    console.log("Finally will run in any condition");
// Close the file
// Exit the Loop
// Write to the log file
}
}
console.log("End");
f();
